### ISSUE TITLE
Improve mock typings and front interface

### ISSUE THREAD

**Issue by Pmyl** [uittorio/ts-auto-mock#13]
```ts
export type Mock<T> = T & { ___thisIsAMockMarker: boolean };
```
This is horrible.

And it was my idea. Bad Giulio.

I have an alternative for this. During `On.Mock(myMock)` instead of giving an error at development time I would give an error at runtime.

Let's remove the type `Mock<T>` and just return `T` from `createMock()`. During `On.Mock(myMock)` we just check if `___thisIsAMockMarker` is defined (we don't care about the value) and if it doesn't we throw an Error that says that the provided mock is not recognized as a mock object.

If we then want to remove `___thisIsAMockMarker` we can use other techniques (e.g. all the mocks objects are created from a class and we test it with `instanceof`) but at that point we will still keep the same interface and everything will be retrocompatible.

**Comment by uittorio** [comment]
I agree :) I’ve honestly just copied and paste your idea ahahah :). I dont mind use the object as “instance”. If it grows we will add a proper class
