### ISSUE TITLE
ts_auto_mock_1.createMock is not a function

### ISSUE THREAD

**Issue by uittorio** [uittorio/ts-auto-mock#66]
This issue happened in windows environment using git bash. the transformer is not able to find the createMock function, so it will not convert the mock.

If you run npm run test:debug it will log the differences between the paths

The ideal solution is to make sure the path comparison is environment compatible, using path join in the transformer matcher

**Comment by rahmatrhd** [comment]
I use `mocha` and I run the test like this:

```
npx mocha -r ts-node/register **/*.spec.ts
```

and it returned error `ts_auto_mock_1.createMock is not a function`. I'm not sure whether this is the same as your issue.

> The ideal solution is to make sure the path comparison is environment compatible, using path join in the transformer matcher

Can you elaborate more on this ☝️?

**Comment by uittorio** [comment]
Hi @rahmatrhd. that error indicates that the transformer has not been applied. Do you have a repo where I can check if the configuration has been done correctly for ts-auto-mock?

**Comment by Pmyl** [comment]
@rahmatrhd ts-node configuration accept custom transformers in a very similar way of awesome-typescript-loader and ts-loader, if you follow the guide that uittorio linked it should be fine.

If you can’t figure out how to do it or it doesn’t work for any other reason join us on slack, we will be available to help you! You can find the slack channel in the readme of this project

**Comment by Pmyl** [comment]
@rahmatrhd I updated the guide page to include **ts-node** with **mocha** examples, you can find it here https://github.com/Typescript-TDD/ts-auto-mock/blob/master/docs/TRANSFORMER.md.

I hope it helps!

**Comment by rahmatrhd** [comment]
Great thanks, @Pmyl and @uittorio !!
It's working now after I implement the transformers based on the docs!

But actually I got a different error now, I'll create an issue

**Comment by abou7mied** [comment]
I'm facing the same issue even after registering the transformer to ts-node

```js
import 'mocha';
import { createMock } from 'ts-auto-mock';
import { register } from 'ts-node';
import { Program } from 'typescript';
import chai from 'chai';

const tsAutoMockTransformer = require('ts-auto-mock/transformer').default;

const { expect } = chai;

register({
  transformers: (program: Program) => ({
    before: [
      tsAutoMockTransformer(program),
    ],
  }),
});

describe('First test', () => {
  it('should not equals undefined', () => {
    expect(createMock)
      .not
      .equal(undefined);
  });
});
```

typescript: 3.6.3
ts-node: 8.5.4
ts-auto-mock: 1.4.2
mocha: 5.2.0

**Comment by uittorio** [comment]
Hi @abou7mied, 

I am not familiar with mocha but if you read the guide it looks like that the register file is separated from the test files.

This is the link, did you follow the guide for ts node and mocha?

https://github.com/Typescript-TDD/ts-auto-mock/blob/master/docs/TRANSFORMER.md

It could be that i’m completely wrong.
@Pmyl may have a better idea :)

**Comment by sklinov** [comment]
Hi, @uittorio !
I'm facing that issue too trying to test Redux actions in Gatsby project. 
I'm getting `TypeError: (0 , _tsAutoMock.createMock) is not a function`.
Here's my `tsconfig.json`
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "esnext",
    "jsx": "preserve",
    "lib": ["dom", "es2015", "es2017"],
    "strict": true,
    "noEmit": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": false,
    "preserveConstEnums": true,
    "plugins": [
      { "transform": "ts-auto-mock/transformer", "cacheBetweenTests": false }
    ]
  },
  "include": ["./src/**/*", "jest"]
}
```
`package.json`
```
...
  "jest": {
    "preset": "ts-jest",
    "globals": {
      "ts-jest": {
        "compiler": "ttypescript"
      }
    }
  }
...
```
`jest.config.js`
```
module.exports = {
  transform: {
    // "^.+\\.(tsx?|jsx?)$": "ts-jest",
    "\\.svg": "<rootDir>/jest/__mocks__/svgTransform.js" ,
    "^.+\\.(tsx?|jsx?)$": `<rootDir>/jest/jest-preprocess.js`,
  },
  moduleNameMapper: {
    "\\.svg": `<rootDir>/jest/__mocks__/svgTransform.js`,
    "typeface-*": "identity-obj-proxy",
    ".+\\.(css|styl|less|sass|scss)$": `identity-obj-proxy`,
    // ".+\\.(jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": `<rootDir>/jest-configs/__mocks__/file-mocks.js`
  },
  testPathIgnorePatterns: [`node_modules`, `.cache`, `public`],
  transformIgnorePatterns: [`node_modules/(?!(gatsby)/)`],
  globals: {
    __PATH_PREFIX__: ``,
  },
  testURL: `http://localhost`,
  setupFiles: [`<rootDir>/loadershim.js`],
}
```

**Comment by uittorio** [comment]
Hi @sklinov , can you double check if ttypescript is installed ?. Unfortunately I can not look into it for the next 4 5 hours. @Pmyl may be able to help you later. In the mean time can you try to share a repo so I can find out the bug easily? Thanks in advance for using the library and the patience :)

**Comment by sklinov** [comment]
@uittorio , you were right that `ttypescript` was not in my `package.json`, but adding it didn't solve the problem.
Unfortunately, I can't share the repo that easy (it's private GitLab), but can show you the necessary parts of the code.
Thanks for the quick reply!

**Comment by sklinov** [comment]
@uittorio also, if that is important I have this 
`jest-preprocess.js` file mentioned in `jest.config.js`
```
const babelOptions = {
  presets: [
    '@babel/preset-react',
    'babel-preset-gatsby',
    "@babel/preset-typescript"
  ],
};

module.exports = require("babel-jest").createTransformer(babelOptions)
```

**Comment by uittorio** [comment]
That is a good point, Im not sure how its compiling, if its doing typescript first or not. You could try to remove that babel pre processor to confirm it. Currently ts auto mock works only with typescript compilation. If you want to compile with babel it will not work, you can just change the pattern from tsx to jsx for babel

**Comment by uittorio** [comment]
Ill try to reproduce your environment later :) thanks for all the info

**Comment by sklinov** [comment]
@uittorio Thanks, I'll try to do that.
Actually, I was just trying to follow [the official Gatsby way](https://www.gatsbyjs.org/docs/unit-testing/) of testing and [this little tutorial ](https://dev.to/k0d3d/unit-testing-for-gatsby-using-jest-typescript-and-react-testing-library-i7p) as I'm using Typescript

**Comment by typescripttdd** [comment]
@sklinov sorry for the late reply. I've tried to reproduce the issue but everything looks all right. 

Here is a zip file with an example where I've tried to use the same configuration that you use.

[Archive.zip](https://github.com/Typescript-TDD/ts-auto-mock/files/4259208/Archive.zip)

Can you share with me your package.json and loadhershim?

**Comment by sklinov** [comment]
@typescripttdd 
Thanks, I'll look into your archive.
Here's my `package.json`
```
{
  "name": "name",
  "description": "description",
  "version": "1.0.0",
  "private": true,
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "hook:email": "hook-email @my-domain-name.com",
    "build": "rm -rf .cache && rm -rf public && gatsby build",
    "gcp-build": "rm -rf .cache && rm -rf public && gatsby build",
    "clean": "rimraf public",
    "dev": "gatsby develop",
    "serve": "gatsby serve",
    "format": "prettier --write \"src/**/*.{ts,tsx,md}\"",
    "lint": "eslint 'src/**/*.{ts,tsx}'",
    "start": "node server.js",
    "test": "jest",
    "type-check-link": "npm run type-check && npm run lint",
    "type-check": "tsc",
    "graphql-types": "gql-gen"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "dependencies": {
    "@altermeliora/payform-types": "^0.1.2",
    "@apollo/react-hooks": "^3.1.3",
    "@emotion/core": "^10.0.22",
    "@emotion/styled": "^10.0.23",
    "@reach/router": "^1.2.1",
    "@types/country-list": "^2.1.0",
    "@types/googlemaps": "^3.39.2",
    "@types/lodash": "^4.14.149",
    "@types/node-fetch": "^2.5.4",
    "@types/reach__router": "^1.2.6",
    "@types/react-image-gallery": "^0.9.2",
    "@types/react-redux": "^7.1.5",
    "@types/react-responsive": "^8.0.2",
    "@types/react-test-renderer": "^16.9.2",
    "@types/redux": "^3.6.0",
    "@types/redux-devtools": "^3.0.47",
    "@types/redux-saga": "^0.10.5",
    "antd": "^3.25.3",
    "apollo-boost": "^0.4.4",
    "babel-plugin-import": "^1.13.0",
    "babel-plugin-styled-components": "^1.10.6",
    "change-case": "^3.1.0",
    "classnames": "^2.2.6",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "gatsby": "^2.17.15",
    "gatsby-image": "^2.2.33",
    "gatsby-plugin-antd": "^2.1.0",
    "gatsby-plugin-canonical-urls": "^2.1.15",
    "gatsby-plugin-config": "^1.0.7",
    "gatsby-plugin-emotion": "^4.1.15",
    "gatsby-plugin-favicon": "^3.1.6",
    "gatsby-plugin-i18n": "^1.0.1",
    "gatsby-plugin-less": "^3.0.15",
    "gatsby-plugin-react-helmet": "^3.1.15",
    "gatsby-plugin-react-redux": "^1.1.0-0",
    "gatsby-plugin-sass": "^2.1.24",
    "gatsby-plugin-sharp": "^2.4.0",
    "gatsby-plugin-typescript": "^2.1.18",
    "gatsby-remark-copy-linked-files": "^2.1.30",
    "gatsby-remark-images": "^3.1.31",
    "gatsby-remark-images-contentful": "^2.1.30",
    "gatsby-remark-prismjs": "^3.3.23",
    "gatsby-remark-responsive-iframe": "^2.2.27",
    "gatsby-remark-smartypants": "^2.1.16",
    "gatsby-source-contentful": "^2.1.79",
    "gatsby-source-filesystem": "^2.1.37",
    "gatsby-transformer-json": "^2.2.18",
    "gatsby-transformer-remark": "^2.6.36",
    "gatsby-transformer-sharp": "^2.3.13",
    "gatsby-transformer-sqip": "^2.1.59",
    "html-react-parser": "^0.10.0",
    "i18n-iso-countries": "^4.3.1",
    "i18next": "^19.0.2",
    "intl": "^1.2.5",
    "jest-mock-extended": "^1.0.8",
    "jest-ts-auto-mock": "^1.0.11",
    "less": "^3.10.3",
    "libphonenumber-js": "^1.7.29",
    "lodash": "^4.17.15",
    "modern-normalize": "^0.5.0",
    "node-fetch": "^2.6.0",
    "node-open-geocoder": "^4.0.1",
    "node-sass": "^4.13.0",
    "normalize.css": "^8.0.1",
    "polished": "^3.4.2",
    "prism-themes": "^1.3.0",
    "prismjs": "^1.17.1",
    "ptz-i18n": "^1.0.0",
    "react": "^16.12.0",
    "react-country-flag": "^2.0.1",
    "react-dom": "^16.12.0",
    "react-helmet": "^5.2.1",
    "react-i18next": "^11.2.6",
    "react-image-gallery": "^0.9.1",
    "react-intl": "^3.6.0",
    "react-redux": "^7.1.3",
    "react-responsive": "^8.0.1",
    "react-select-country-list": "^2.0.1",
    "react-slick": "^0.25.2",
    "redux": "^4.0.4",
    "redux-devtools-extension": "^2.13.8",
    "redux-dynamic-modules": "^5.2.0",
    "redux-dynamic-modules-saga": "^5.2.0",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3",
    "slash": "^3.0.0",
    "slick-carousel": "^1.8.1",
    "transliteration": "^2.1.8",
    "ts-auto-mock": "^1.5.6",
    "ttypescript": "^1.5.10",
    "typescript": "^3.7.2"
  },
  "devDependencies": {
    "@testing-library/react": "^9.4.1",
    "@types/classnames": "^2.2.9",
    "@types/intl": "^1.2.0",
    "@types/jest": "^25.1.3",
    "@types/node": "^12.12.8",
    "@types/react": "^16.9.11",
    "@types/react-dom": "^16.9.4",
    "@types/react-helmet": "^5.0.14",
    "@types/react-intl": "^3.0.0",
    "@typescript-eslint/eslint-plugin": "^2.7.0",
    "@typescript-eslint/parser": "^2.7.0",
    "babel-jest": "^25.1.0",
    "babel-preset-gatsby": "^0.2.29",
    "eslint": "^6.6.0",
    "eslint-config-blvd": "^1.0.0",
    "eslint-config-prettier": "^6.6.0",
    "eslint-plugin-prettier": "^3.1.1",
    "gh-pages": "^2.1.1",
    "graphql-code-generator": "^0.18.2",
    "graphql-codegen-typescript-client": "^0.18.2",
    "graphql-codegen-typescript-common": "^0.18.2",
    "graphql-codegen-typescript-server": "^0.18.2",
    "hook-email": "^1.0.2",
    "husky": "^3.1.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^25.1.0",
    "prettier": "^1.19.1",
    "react-test-renderer": "^16.12.0",
    "redux-devtools": "^3.5.0",
    "rimraf": "^3.0.0",
    "ts-jest": "^25.2.1"
  },
  "jest": {
    "preset": "ts-jest",
    "globals": {
      "ts-jest": {
        "compiler": "ttypescript"
      }
    }
  }
}

```
and `loadershim.js`
```
global.___loader = {
  enqueue: jest.fn(),
}
```

**Comment by uittorio** [comment]
I can see that you have a jest config in your package json that doesnt include ts-jest for the tsx pttern match. You could try to add it also in the package json

**Comment by uittorio** [comment]
@sklinov I've added a small guide for jest + ts jest. https://typescript-tdd.github.io/ts-auto-mock/installation#jest--ts-jest--ttypescript. Let me know if it helped.

**Comment by sklinov** [comment]
@uittorio Thanks for adding that guide.
I've tried to reproduce the configuration from that guide and archive file you sent me earlier, but still get that `TypeError: ts_auto_mock_1.createMock is not a function`
on my test:
```
import { createMock } from 'ts-auto-mock';
import {
  ActionTypes,
  SetCartStatusActionCreator,
  AddToCartActionCreator,
} from '../cart.actions';
import { CartItem } from '../../../lib/common-interfaces';

describe('Redux - Cart - Actions', () => {

  test('Set cart status action creator', () => {
    const payload = {
      loading: true,
    };
    const expectedActionObject = {
      payload,
      type: ActionTypes.SET_CART_STATUS,
    };
    expect(SetCartStatusActionCreator(payload)).toEqual(expectedActionObject);
  });

  test('Add to cart action creator', () => {
    const cartItem = createMock<CartItem>();
    const expectedActionObject = {
      cartItem,
      type: ActionTypes.SET_CART_STATUS,
    };
    expect(AddToCartActionCreator(cartItem)).toEqual(expectedActionObject);
  });
});

```
My thought is that it has to do with running together with Gatsby and they test config they provide.
I'll keep looking at what can I do about the config and get back if I have any positive results.

**Comment by uittorio** [comment]
I'll also try to install gatbsy and use it. Is there any starting guide that I can use?

**Comment by sklinov** [comment]
@uittorio Thanks! They have this [Quick Start Guide](https://www.gatsbyjs.org/docs/quick-start/). Just make sure you have a TypeScript option on the project init. Please, let me know if you have any trouble with that.

**Comment by uittorio** [comment]
@sklinov sorry for the delay. I am currently in a country where the connection is not that great. I've successfully used ts-auto-mock with gatbsy. No Babel. 
Please bare in mind that we don't support yet typescript 3.8.X (I will work on that as soon as I have a better connection)

[gatbsy-test.zip](https://github.com/Typescript-TDD/ts-auto-mock/files/4269907/gatbsy-test.zip)

**Comment by sklinov** [comment]
@uittorio Actually your config for the Gatsby did help - so I was able to run the tests.
Thanks for your patience and support!

**Comment by sklinov** [comment]
@uittorio 
And it's me again, sorry.
Ran into the same issue again in 'create-react-app' application.

[configs.zip](https://github.com/Typescript-TDD/ts-auto-mock/files/4358381/configs.zip)

**Comment by uittorio** [comment]
Hi @sklinov. Can you join me on slack, I can give you more support from there. [Here](https://join.slack.com/t/typescripttdd/shared_invite/enQtODk3MjQwNzUwNTk2LTMzNjdlZTNmMmY3Nzg2NDNiZDA1YzJmZjk2NjcwZjQwODQ3YzE5NGZjM2Q4MzZjYWNiMWE4MGU0NjEzM2E5YzE) the invitation link
